web: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
worker: celery -A core.celery_app worker --loglevel=info --concurrency=2
beat: celery -A core.celery_app beat --loglevel=info
