const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'frontend/src/i18n/locales');
const langs = ['en', 'tr', 'fr', 'de', 'es', 'zh', 'su'];

const newKeys = {
    en: {
        dashboard: {
            magicTemplatesTitle: "Magic Templates",
            oneClickGen: "One-Click Gen",
            cyberpunkTemplateTitle: "Cyberpunk City",
            portraitTemplateTitle: "Cinematic Portrait",
            landscapeTemplateTitle: "Dreamy Landscape",
            characterTemplateTitle: "3D Character",
            useTemplate: "Use Template",
            quickActionsTitle: "Quick Actions",
            genImage: "Generate Image",
            genImageDesc: "AI images",
            genVideo: "Generate Video",
            genVideoDesc: "Text to video",
            popularBadge: "Popular",
            audioTools: "Audio Tools",
            audioToolsDesc: "TTS & Music",
            aiChat: "AI Chat",
            aiChatDesc: "Smart assistant",
            synapse: "Synapse",
            synapseDesc: "Compare models",
            newBadge: "New",
            library: "Library",
            libraryDesc: "All content",
            recentActivitiesTitle: "Recent Activities",
            seeAll: "See All",
            noActivityTitle: "No activity yet",
            noActivityDesc: "When you use an AI service, your activities will appear here.",
            aiGeneration: "AI Generation",
            creditsSpentRow: "-{{count}} credits",
            marketplacePromoTitle: "Model Marketplace",
            marketplacePromoDesc: "Choose from 40+ AI models",
            discoverBtn: "Discover",
            passiveIncomeBadge: "\u2728 Passive Income",
            lifetimeEarnTitle: "1% Lifetime Earnings",
            lifetimeEarnDesc: "From all purchases of people you invite",
            startNowBtn: "\ud83d\ude80 Start Now",
            dailySummary: "Today's summary of your AI services",
            tipHeader: "\ud83d\udca1 Tip of the Day",
            tip1Header: "\ud83d\udca1 Tip of the Day",
            tip1Content: "Get the best results by comparing different AI models with Synapse!",
            tip2Header: "\ud83c\udfaf Info",
            tip2Content: "Invite your friends with the referral program, both of you earn credits!",
            tip3Header: "\u2728 Suggestion",
            tip3Content: "Get higher quality results by writing detailed prompts when generating video.",
            tip4Header: "\ud83d\ude80 New",
            tip4Content: "You can choose from 40+ different AI models in the Marketplace!"
        }
    },
    tr: {
        dashboard: {
            magicTemplatesTitle: "Sihirli \u015eablonlar",
            oneClickGen: "Tek T\u0131kla \u00dcret",
            cyberpunkTemplateTitle: "Cyberpunk \u015eehir",
            portraitTemplateTitle: "Sinematik Portre",
            landscapeTemplateTitle: "R\u00fcya Manzaras\u0131",
            characterTemplateTitle: "3D Karakter",
            useTemplate: "\u015eablonu Kullan",
            quickActionsTitle: "H\u0131zl\u0131 Aksiyonlar",
            genImage: "G\u00f6rsel Olu\u015ftur",
            genImageDesc: "AI ile g\u00f6rseller",
            genVideo: "Video Olu\u015ftur",
            genVideoDesc: "Metin'den video",
            popularBadge: "Pop\u00fcler",
            audioTools: "Ses Ara\u00e7lar\u0131",
            audioToolsDesc: "TTS & M\u00fczik",
            aiChat: "AI Sohbet",
            aiChatDesc: "Ak\u0131ll\u0131 asistan",
            synapse: "Synapse",
            synapseDesc: "Model kar\u015f\u0131la\u015ft\u0131r",
            newBadge: "Yeni",
            library: "K\u00fct\u00fcphane",
            libraryDesc: "T\u00fcm i\u00e7erikler",
            recentActivitiesTitle: "Son Aktiviteler",
            seeAll: "T\u00fcm\u00fcn\u00fc G\u00f6r",
            noActivityTitle: "Hen\u00fcz aktivite yok",
            noActivityDesc: "Bir AI hizmeti kulland\u0131\u011f\u0131n\u0131zda aktiviteleriniz burada g\u00f6r\u00fcn\u00fcr.",
            aiGeneration: "AI \u00dcretimi",
            creditsSpentRow: "-{{count}} kredi",
            marketplacePromoTitle: "Model Marketplace",
            marketplacePromoDesc: "40+ AI modeli aras\u0131ndan se\u00e7im yap\u0131n",
            discoverBtn: "Ke\u015ffet",
            passiveIncomeBadge: "\u2728 Pasif Gelir",
            lifetimeEarnTitle: "%1 \u00d6m\u00fcr Boyu Kazan\u00e7",
            lifetimeEarnDesc: "Davet etti\u011fin ki\u015filerin t\u00fcm al\u0131\u015fveri\u015flerinden",
            startNowBtn: "\ud83d\ude80 Hemen Ba\u015fla",
            dailySummary: "AI hizmetlerinizin bug\u00fcnk\u00fc \u00f6zeti",
            tipHeader: "\ud83d\udca1 G\u00fcn\u00fcn \u0130pucu",
            tip1Header: "\ud83d\udca1 G\u00fcn\u00fcn \u0130pucu",
            tip1Content: "Synapse ile farkl\u0131 AI modellerini kar\u015f\u0131la\u015ft\u0131rarak en iyi sonucu al\u0131n!",
            tip2Header: "\ud83c\udfaf Bilgi",
            tip2Content: "Referans program\u0131yla arkada\u015flar\u0131n\u0131z\u0131 davet edin, hem siz hem onlar kredi kazans\u0131n!",
            tip3Header: "\u2728 \u00d6neri",
            tip3Content: "Video olu\u015ftururken detayl\u0131 prompt yazarak daha kaliteli sonu\u00e7lar elde edin.",
            tip4Header: "\ud83d\ude80 Yenilik",
            tip4Content: "Marketplace'te 40+ farkl\u0131 AI modeli aras\u0131ndan se\u00e7im yapabilirsiniz!"
        }
    },
    fr: {
        dashboard: {
            magicTemplatesTitle: "Mod\u00e8les Magiques",
            oneClickGen: "G\u00e9n en un clic",
            cyberpunkTemplateTitle: "Ville Cyberpunk",
            portraitTemplateTitle: "Portrait Cin\u00e9matique",
            landscapeTemplateTitle: "Paysage de R\u00eave",
            characterTemplateTitle: "Personnage 3D",
            useTemplate: "Utiliser le mod\u00e8le",
            quickActionsTitle: "Actions Rapides",
            genImage: "Cr\u00e9er une Image",
            genImageDesc: "Images IA",
            genVideo: "Cr\u00e9er une Vid\u00e9o",
            genVideoDesc: "Texte vers vid\u00e9o",
            popularBadge: "Populaire",
            audioTools: "Outils Audio",
            audioToolsDesc: "TTS & Musique",
            aiChat: "Chat IA",
            aiChatDesc: "Assistant intelligent",
            synapse: "Synapse",
            synapseDesc: "Comparer mod\u00e8les",
            newBadge: "Nouveau",
            library: "Biblioth\u00e8que",
            libraryDesc: "Tout le contenu",
            recentActivitiesTitle: "Activit\u00e9s R\u00e9centes",
            seeAll: "Voir Tout",
            noActivityTitle: "Aucune activit\u00e9",
            noActivityDesc: "Lorsque vous utilisez un service IA, vos activit\u00e9s appara\u00eetront ici.",
            aiGeneration: "G\u00e9n\u00e9ration IA",
            creditsSpentRow: "-{{count}} cr\u00e9dits",
            marketplacePromoTitle: "Boutique de Mod\u00e8les",
            marketplacePromoDesc: "Choisissez parmi 40+ mod\u00e8les IA",
            discoverBtn: "D\u00e9couvrir",
            passiveIncomeBadge: "\u2728 Revenu Passif",
            lifetimeEarnTitle: "1% de Gains \u00e0 Vie",
            lifetimeEarnDesc: "Sur tous les achats de vos invit\u00e9s",
            startNowBtn: "\ud83d\ude80 Commencer",
            dailySummary: "R\u00e9sum\u00e9 du jour de vos services IA",
            tipHeader: "\ud83d\udca1 Astuce du Jour",
            tip1Header: "\ud83d\udca1 Astuce du Jour",
            tip1Content: "Obtenez les meilleurs r\u00e9sultats en comparant diff\u00e9rents mod\u00e8les IA avec Synapse !",
            tip2Header: "\ud83c\udfaf Info",
            tip2Content: "Invitez vos amis avec le programme de parrainage, tout le monde gagne des cr\u00e9dits !",
            tip3Header: "\u2728 Suggestion",
            tip3Content: "\u00c9crivez des prompts d\u00e9taill\u00e9s pour des vid\u00e9os de meilleure qualit\u00e9.",
            tip4Header: "\ud83d\ude80 Nouveau",
            tip4Content: "Vous pouvez choisir parmi 40+ mod\u00e8les IA diff\u00e9rents dans la Boutique !"
        }
    },
    de: {
        dashboard: {
            magicTemplatesTitle: "Magische Vorlagen",
            oneClickGen: "1-Klick-Gen",
            cyberpunkTemplateTitle: "Cyberpunk-Stadt",
            portraitTemplateTitle: "Filmportr\u00e4t",
            landscapeTemplateTitle: "Traumlandschaft",
            characterTemplateTitle: "3D-Charakter",
            useTemplate: "Vorlage nutzen",
            quickActionsTitle: "Schnelle Aktionen",
            genImage: "Bild erstellen",
            genImageDesc: "KI-Bilder",
            genVideo: "Video erstellen",
            genVideoDesc: "Text zu Video",
            popularBadge: "Beliebt",
            audioTools: "Audio-Tools",
            audioToolsDesc: "TTS & Musik",
            aiChat: "KI-Chat",
            aiChatDesc: "Smarter Assistent",
            synapse: "Synapse",
            synapseDesc: "Modelle vergl.",
            newBadge: "Neu",
            library: "Bibliothek",
            libraryDesc: "Alle Inhalte",
            recentActivitiesTitle: "Letzte Aktivit\u00e4ten",
            seeAll: "Alle ansehen",
            noActivityTitle: "Noch keine Aktivit\u00e4t",
            noActivityDesc: "Wenn Sie KI nutzen, erscheinen Ihre Aktivit\u00e4ten hier.",
            aiGeneration: "KI-Generierung",
            creditsSpentRow: "-{{count}} Credits",
            marketplacePromoTitle: "Modell-Marktplatz",
            marketplacePromoDesc: "W\u00e4hlen Sie aus 40+ KI-Modellen",
            discoverBtn: "Entdecken",
            passiveIncomeBadge: "\u2728 Passives Einkommen",
            lifetimeEarnTitle: "1% Lebenslanger Verdienst",
            lifetimeEarnDesc: "Aus allen K\u00e4ufen von Eingeladenen",
            startNowBtn: "\ud83d\ude80 Jetzt Starten",
            dailySummary: "Heutige Zusammenfassung",
            tipHeader: "\ud83d\udca1 Tipp des Tages",
            tip1Header: "\ud83d\udca1 Tipp des Tages",
            tip1Content: "Vergleichen Sie verschiedene KI-Modelle mit Synapse f\u00fcr beste Ergebnisse!",
            tip2Header: "\ud83c\udfaf Info",
            tip2Content: "Laden Sie Freunde ein und verdienen Sie beide Credits!",
            tip3Header: "\u2728 Vorschlag",
            tip3Content: "Schreiben Sie detaillierte Prompts f\u00fcr noch bessere Videos.",
            tip4Header: "\ud83d\ude80 Neu",
            tip4Content: "W\u00e4hlen Sie aus 40+ KI-Modellen im Marktplatz!"
        }
    },
    es: {
        dashboard: {
            magicTemplatesTitle: "Plantillas M\u00e1gicas",
            oneClickGen: "Gen. 1 Clic",
            cyberpunkTemplateTitle: "Ciudad Cyberpunk",
            portraitTemplateTitle: "Retrato Cinem\u00e1tico",
            landscapeTemplateTitle: "Paisaje de Ensue\u00f1o",
            characterTemplateTitle: "Personaje 3D",
            useTemplate: "Usar Plantilla",
            quickActionsTitle: "Acciones R\u00e1pidas",
            genImage: "Crear Imagen",
            genImageDesc: "Im\u00e1genes IA",
            genVideo: "Crear Video",
            genVideoDesc: "Texto a video",
            popularBadge: "Popular",
            audioTools: "Herr. de Audio",
            audioToolsDesc: "TTS y m\u00fasica",
            aiChat: "Chat IA",
            aiChatDesc: "Asistente intel.",
            synapse: "Synapse",
            synapseDesc: "Comp. modelos",
            newBadge: "Nuevo",
            library: "Biblioteca",
            libraryDesc: "Todo el cont.",
            recentActivitiesTitle: "Actividades Recientes",
            seeAll: "Ver Todo",
            noActivityTitle: "Sin actividad a\u00fan",
            noActivityDesc: "Tus actividades de IA aparecer\u00e1n aqu\u00ed.",
            aiGeneration: "Generaci\u00f3n IA",
            creditsSpentRow: "-{{count}} cr\u00e9ditos",
            marketplacePromoTitle: "Mercado de Modelos",
            marketplacePromoDesc: "Elige entre 40+ modelos de IA",
            discoverBtn: "Descubrir",
            passiveIncomeBadge: "\u2728 Ingreso Pasivo",
            lifetimeEarnTitle: "1% de Ganancias de por Vida",
            lifetimeEarnDesc: "De las compras de tus invitados",
            startNowBtn: "\ud83d\ude80 Empezar",
            dailySummary: "Resumen de hoy",
            tipHeader: "\ud83d\udca1 Consejo del D\u00eda",
            tip1Header: "\ud83d\udca1 Consejo del D\u00eda",
            tip1Content: "\u00a1Obt\u00e9n los mejores resultados comparando modelos de IA con Synapse!",
            tip2Header: "\ud83c\udfaf Info",
            tip2Content: "\u00a1Invita amigos con el programa de referidos, ambos ganan cr\u00e9ditos!",
            tip3Header: "\u2728 Sugerencia",
            tip3Content: "Escribe prompts detallados para obtener videos de mayor calidad.",
            tip4Header: "\ud83d\ude80 Nuevo",
            tip4Content: "\u00a1Elige entre 40+ diferentes modelos de IA en el Mercado!"
        }
    },
    zh: {
        dashboard: {
            magicTemplatesTitle: "\u9b54\u6cd5\u6a21\u677f",
            oneClickGen: "\u4e00\u952e\u751f\u6210",
            cyberpunkTemplateTitle: "\u8d5b\u535a\u670b\u514b\u57ce\u5e02",
            portraitTemplateTitle: "\u7535\u5f71\u7ea7\u8096\u50cf",
            landscapeTemplateTitle: "\u68a6\u5e7b\u98ce\u666f",
            characterTemplateTitle: "3D \u89d2\u8272",
            useTemplate: "\u4f7f\u7528\u6a21\u677f",
            quickActionsTitle: "\u5feb\u6377\u64cd\u4f5c",
            genImage: "\u751f\u6210\u56fe\u50cf",
            genImageDesc: "AI \u56fe\u50cf",
            genVideo: "\u751f\u6210\u89c6\u9891",
            genVideoDesc: "\u6587\u672c\u8f6c\u89c6\u9891",
            popularBadge: "\u70ed\u95e8",
            audioTools: "\u97f3\u9891\u5de5\u5177",
            audioToolsDesc: "TTS \u4e0e\u97f3\u4e50",
            aiChat: "AI \u804a\u5929",
            aiChatDesc: "\u667a\u80fd\u52a9\u624b",
            synapse: "Synapse",
            synapseDesc: "\u6a21\u578b\u5bf9\u6bd4",
            newBadge: "\u65b0",
            library: "\u5a92\u4f53\u5e93",
            libraryDesc: "\u6240\u6709\u5185\u5bb9",
            recentActivitiesTitle: "\u6700\u8fd1\u6d3b\u52a8",
            seeAll: "\u67e5\u770b\u5168\u90e8",
            noActivityTitle: "\u6682\u65e0\u6d3b\u52a8",
            noActivityDesc: "\u5f53\u60a8\u4f7f\u7528AI\u670d\u52a1\u65f6\uff0c\u60a8\u7684\u6d3b\u52a8\u5c06\u663e\u793a\u5728\u8fd9\u91cc\u3002",
            aiGeneration: "AI\u751f\u6210",
            creditsSpentRow: "-{{count}} \u79ef\u5206",
            marketplacePromoTitle: "\u6a21\u578b\u5e02\u573a",
            marketplacePromoDesc: "\u4ece 40+ AI \u6a21\u578b\u4e2d\u9009\u62e9",
            discoverBtn: "\u63a2\u7d22",
            passiveIncomeBadge: "\u2728 \u88ab\u52a8\u6536\u5165",
            lifetimeEarnTitle: "1% \u7ec8\u8eab\u6536\u76ca",
            lifetimeEarnDesc: "\u6765\u81ea\u60a8\u9080\u8bf7\u7684\u4eba\u7684\u6240\u6709\u8d2d\u4e70",
            startNowBtn: "\ud83d\ude80 \u7acb\u5373\u5f00\u59cb",
            dailySummary: "\u4eca\u65e5AI\u670d\u52a1\u4f7f\u7528\u6458\u8981",
            tipHeader: "\ud83d\udca1 \u6bcf\u65e5\u63d0\u793a",
            tip1Header: "\ud83d\udca1 \u6bcf\u65e5\u63d0\u793a",
            tip1Content: "\u4f7f\u7528 Synapse \u5bf9\u6bd4\u4e0d\u540c AI \u6a21\u578b\uff0c\u83b7\u53d6\u6700\u4f73\u7ed3\u679c\uff01",
            tip2Header: "\ud83c\udfaf \u4fe1\u606f",
            tip2Content: "\u9080\u8bf7\u597d\u53cb\u53c2\u4e0e\u63a8\u8350\u8ba1\u5212\uff0c\u53cc\u65b9\u90fd\u80fd\u83b7\u5f97\u79ef\u5206\uff01",
            tip3Header: "\u2728 \u5efa\u8bae",
            tip3Content: "\u5728\u751f\u6210\u89c6\u9891\u65f6\u7f16\u5199\u8be6\u7ec6\u7684\u63d0\u793a\u8bcd\u4ee5\u83b7\u5f97\u66f4\u9ad8\u8d28\u91cf\u7684\u7ed3\u679c\u3002",
            tip4Header: "\ud83d\ude80 \u65b0",
            tip4Content: "\u60a8\u53ef\u4ee5\u5728\u5e02\u573a\u4e0a\u4ece 40+ \u79cd\u4e0d\u540c\u7684 AI \u6a21\u578b\u4e2d\u8fdb\u884c\u9009\u62e9\uff01"
        }
    },
    su: {
        dashboard: {
            magicTemplatesTitle: "Zubi Mah",
            oneClickGen: "Diš Dù",
            cyberpunkTemplateTitle: "Uru Cyber",
            portraitTemplateTitle: "Alam Zubi",
            landscapeTemplateTitle: "Ma-da Múš",
            characterTemplateTitle: "3D Lú",
            useTemplate: "Zubi Kú",
            quickActionsTitle: "Hé-gal",
            genImage: "Alam Dù",
            genImageDesc: "Alam An",
            genVideo: "Zubi Dù",
            genVideoDesc: "Gù-Zubi",
            popularBadge: "Ug3",
            audioTools: "Šìr Giš",
            audioToolsDesc: "Gù & Šìr",
            aiChat: "KA-bal An",
            aiChatDesc: "Sukkal",
            synapse: "Synapse",
            synapseDesc: "Dim-dim Igi",
            newBadge: "Gibil",
            library: "É-dub",
            libraryDesc: "Níg-nam",
            recentActivitiesTitle: "Dù Gibil",
            seeAll: "Níg Igi",
            noActivityTitle: "Nu Dù",
            noActivityDesc: "An ki gub-ba-a, dù-dù-zu ki-a pà-dè.",
            aiGeneration: "An Dù",
            creditsSpentRow: "-{{count}} kú",
            marketplacePromoTitle: "Ki-lam Dim-dim",
            marketplacePromoDesc: "40+ An Dim-dim Igi",
            discoverBtn: "Pà",
            passiveIncomeBadge: "\u2728 Níg Zálag",
            lifetimeEarnTitle: "1% Níg-gál U4",
            lifetimeEarnDesc: "Níg-gál lú gù-dé-za",
            startNowBtn: "\ud83d\ude80 Šur",
            dailySummary: "U4-da me-zu",
            tipHeader: "\ud83d\udca1 Múš U4",
            tip1Header: "\ud83d\udca1 Múš U4",
            tip1Content: "Synapse ki dim-dim igi-gal!",
            tip2Header: "\ud83c\udfaf Zálag",
            tip2Content: "Lú gù-dé, ku4 kú!",
            tip3Header: "\u2728 Dù",
            tip3Content: "Dim-dim zubi šu-du7 sar.",
            tip4Header: "\ud83d\ude80 Gibil",
            tip4Content: "40+ ki-lam dim-dim igi!"
        }
    }
};

langs.forEach(lang => {
    const filePath = path.join(localesDir, `${lang}.json`);
    let data = {};
    if (fs.existsSync(filePath)) {
        try {
            data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        } catch (e) {
            console.error(`Error parsing ${filePath}`);
        }
    }
    Object.assign(data.dashboard, newKeys[lang].dashboard);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
