const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'frontend/src/i18n/locales');
const langs = ['en', 'tr', 'fr', 'de', 'es', 'zh', 'su'];

const newKeys = {
    en: {
        audioGen: {
            badge: "AI Audio Studio",
            title: "Audio ",
            titleHighlight: "Wizard",
            desc: "From text to speech, music generation to voice cloning - create professional audio",
            tabTTS: "Text \u2192 Speech",
            tabMusic: "Music Gen",
            tabVoice: "Voice Clone",
            tabPackages: "Packages",
            tabLibrary: "My Audio",
            ttsTitle: "Convert Text to Speech",
            ttsPlaceholder: "Write the text you want to convert to speech...",
            voiceCharacter: "Voice Character",
            speed: "Speed",
            model: "Model",
            selectModel: "Select model",
            generateBtn: "Generate Audio",
            generating: "Generating...",
            popModelsTitle: "Popular Models",
            musicTitle: "AI Music Generation",
            musicSelectGenre: "Select Genre",
            musicMood: "Mood",
            musicMoods: {
                happy: "Happy",
                sad: "Sad",
                epic: "Epic",
                calm: "Calm",
                energetic: "Energetic",
                romantic: "Romantic"
            },
            musicPlaceholder: "Describe your music... (e.g., Energetic, motivating electronic music for a morning run)",
            musicGenerateBtn: "Generate Music",
            cloneTitle: "Voice Cloning",
            cloneVoiceNameLabel: "Voice Name",
            cloneVoiceNamePlaceholder: "e.g., My Voice",
            cloneAudioFileLabel: "Audio File",
            cloneUploadClick: "Click to upload voice sample",
            cloneUploadChange: "Click to change",
            cloneUploadReqs: "MP3, WAV \u2022 Min. 30 seconds",
            cloneTipsTitle: "\ud83d\udca1 Tips:",
            cloneTip1: "\u2022 Use clean, high-quality audio",
            cloneTip2: "\u2022 Avoid background noise",
            cloneTip3: "\u2022 Min. 30 seconds, ideal 1-2 minutes",
            cloneBtn: "Clone Voice",
            cloning: "Cloning...",
            clonedVoicesTitle: "My Cloned Voices",
            noClonedVoices: "You haven't cloned any voices yet",
            statusReady: "\u2705 Ready",
            statusProcessing: "\u23F3 Processing",
            statusFailed: "\u274c Failed",
            packagesTitle: "Audio Packages",
            discountBadge: "Up to 30% off",
            buyPackageBtn: "Get Package",
            libraryTitle: "My Audio",
            noAudio: "No audio yet",
            createFirstAudio: "Create your first audio!",
            statusReady2: "Ready",
            statusProcessing2: "Processing",
            musicGenres: {
                electronic: "Electronic",
                rock: "Rock",
                jazz: "Jazz",
                classical: "Classical",
                hiphop: "Hip-Hop",
                ambient: "Ambient"
            }
        }
    },
    tr: {
        audioGen: {
            badge: "AI Ses Stüdyosu",
            title: "Ses ",
            titleHighlight: "Sihirbazı",
            desc: "Metinden sese, müzik üretiminden ses klonlamaya - profesyonel sesler oluşturun",
            tabTTS: "Metin \u2192 Ses",
            tabMusic: "Müzik Üretimi",
            tabVoice: "Ses Klonlama",
            tabPackages: "Paketler",
            tabLibrary: "Seslerim",
            ttsTitle: "Metni Sese Dönüştür",
            ttsPlaceholder: "Sese dönüştürmek istediğiniz metni yazın...",
            voiceCharacter: "Ses Karakteri",
            speed: "Hız",
            model: "Model",
            selectModel: "Model seçin",
            generateBtn: "Ses Oluştur",
            generating: "Oluşturuluyor...",
            popModelsTitle: "Popüler Modeller",
            musicTitle: "AI Müzik Üretimi",
            musicSelectGenre: "Tarz Seçin",
            musicMood: "Mood",
            musicMoods: {
                happy: "Mutlu",
                sad: "Hüzünlü",
                epic: "Epik",
                calm: "Sakin",
                energetic: "Enerjik",
                romantic: "Romantik"
            },
            musicPlaceholder: "Müziğinizi tanımlayın... (Örn: Sabah koşusu için enerjik, motive edici elektronik müzik)",
            musicGenerateBtn: "Müzik Oluştur",
            cloneTitle: "Ses Klonlama",
            cloneVoiceNameLabel: "Ses Adı",
            cloneVoiceNamePlaceholder: "Örn: Benim Sesim",
            cloneAudioFileLabel: "Ses Dosyası",
            cloneUploadClick: "Ses örneği yükleyin",
            cloneUploadChange: "Değiştirmek için tıklayın",
            cloneUploadReqs: "MP3, WAV \u2022 Min. 30 saniye",
            cloneTipsTitle: "\ud83d\udca1 İpuçları:",
            cloneTip1: "\u2022 Temiz, yüksek kaliteli ses kullanın",
            cloneTip2: "\u2022 Arka plan gürültüsünden kaçının",
            cloneTip3: "\u2022 Min. 30 saniye, ideal 1-2 dakika",
            cloneBtn: "Ses Klonla",
            cloning: "Klonlanıyor...",
            clonedVoicesTitle: "Klonlanmış Seslerim",
            noClonedVoices: "Henüz klonlanmış sesiniz yok",
            statusReady: "\u2705 Hazır",
            statusProcessing: "\u23F3 İşleniyor",
            statusFailed: "\u274c Başarısız",
            packagesTitle: "Ses Paketleri",
            discountBadge: "%30'a varan indirim",
            buyPackageBtn: "Paketi Al",
            libraryTitle: "Seslerim",
            noAudio: "Henüz ses yok",
            createFirstAudio: "İlk sesinizi oluşturun!",
            statusReady2: "Hazır",
            statusProcessing2: "İşleniyor",
            musicGenres: {
                electronic: "Elektronik",
                rock: "Rock",
                jazz: "Jazz",
                classical: "Klasik",
                hiphop: "Hip-Hop",
                ambient: "Ambient"
            }
        }
    },
    fr: {
        audioGen: {
            badge: "Studio Audio IA",
            title: "Assistant ",
            titleHighlight: "Audio",
            desc: "De texte à voix, création de musique et clonage - créez des audios pros",
            tabTTS: "Texte \u2192 Voix",
            tabMusic: "Création Musique",
            tabVoice: "Clonage Voix",
            tabPackages: "Forfaits",
            tabLibrary: "Mes Audios",
            ttsTitle: "Convertir Texte en Voix",
            ttsPlaceholder: "Écrivez le texte à convertir en voix...",
            voiceCharacter: "Voix du personnage",
            speed: "Vitesse",
            model: "Modèle",
            selectModel: "Sélectionnez un modèle",
            generateBtn: "Générer l'audio",
            generating: "Génération...",
            popModelsTitle: "Modèles Populaires",
            musicTitle: "Création Musique IA",
            musicSelectGenre: "Choisissez le Genre",
            musicMood: "Ambiance",
            musicMoods: {
                happy: "Joyeux",
                sad: "Triste",
                epic: "Épique",
                calm: "Calme",
                energetic: "Énergique",
                romantic: "Romantique"
            },
            musicPlaceholder: "Décrivez votre musique...",
            musicGenerateBtn: "Générer la Musique",
            cloneTitle: "Clonage de Voix",
            cloneVoiceNameLabel: "Nom de la Voix",
            cloneVoiceNamePlaceholder: "Ex : Ma Voix",
            cloneAudioFileLabel: "Fichier Audio",
            cloneUploadClick: "Cliquez pour un échantillon",
            cloneUploadChange: "Cliquez pour changer",
            cloneUploadReqs: "MP3, WAV \u2022 Min. 30 sec",
            cloneTipsTitle: "\ud83d\udca1 Conseils:",
            cloneTip1: "\u2022 Utilisez un son clair",
            cloneTip2: "\u2022 Évitez le bruit de fond",
            cloneTip3: "\u2022 Min 30 sec, idéal 1-2 min",
            cloneBtn: "Cloner la Voix",
            cloning: "Clonage...",
            clonedVoicesTitle: "Mes Voix Clonées",
            noClonedVoices: "Vous n'avez pas cloné de voix",
            statusReady: "\u2705 Prêt",
            statusProcessing: "\u23F3 En cours",
            statusFailed: "\u274c Échoué",
            packagesTitle: "Forfaits Audio",
            discountBadge: "Jusqu'à -30%",
            buyPackageBtn: "Acheter",
            libraryTitle: "Mes Audios",
            noAudio: "Aucun audio",
            createFirstAudio: "Créez votre premier audio!",
            statusReady2: "Prêt",
            statusProcessing2: "En cours",
            musicGenres: {
                electronic: "Électronique",
                rock: "Rock",
                jazz: "Jazz",
                classical: "Classique",
                hiphop: "Hip-Hop",
                ambient: "Ambiant"
            }
        }
    },
    de: {
        audioGen: {
            badge: "KI Audio Studio",
            title: "Audio ",
            titleHighlight: "Assistent",
            desc: "Text zu Sprache, Musik und Stimmen klonen - professionelles Audio erstellen",
            tabTTS: "Text \u2192 Sprache",
            tabMusic: "Musik Gen",
            tabVoice: "Stimmen klonen",
            tabPackages: "Pakete",
            tabLibrary: "Meine Audios",
            ttsTitle: "Text zu Sprache konvertieren",
            ttsPlaceholder: "Schreiben Sie Ihren Text...",
            voiceCharacter: "Stimme",
            speed: "Geschwindigkeit",
            model: "Modell",
            selectModel: "Modell wählen",
            generateBtn: "Audio generieren",
            generating: "Wird generiert...",
            popModelsTitle: "Beliebte Modelle",
            musicTitle: "KI Musik Generierung",
            musicSelectGenre: "Genre wählen",
            musicMood: "Stimmung",
            musicMoods: {
                happy: "Glücklich",
                sad: "Traurig",
                epic: "Episch",
                calm: "Ruhig",
                energetic: "Energisch",
                romantic: "Romantisch"
            },
            musicPlaceholder: "Beschreiben Sie Ihre Musik...",
            musicGenerateBtn: "Musik generieren",
            cloneTitle: "Stimmen klonen",
            cloneVoiceNameLabel: "Name der Stimme",
            cloneVoiceNamePlaceholder: "z.B. Meine Stimme",
            cloneAudioFileLabel: "Audiodatei",
            cloneUploadClick: "Sprachbeispiel hochladen",
            cloneUploadChange: "Zum Ändern klicken",
            cloneUploadReqs: "MP3, WAV \u2022 Min. 30 Sek",
            cloneTipsTitle: "\ud83d\udca1 Tipps:",
            cloneTip1: "\u2022 Sauberes, hochwertiges Audio",
            cloneTip2: "\u2022 Hintergrundgeräusche vermeiden",
            cloneTip3: "\u2022 Min 30s, ideal 1-2 Min",
            cloneBtn: "Stimme klonen",
            cloning: "Wird geklont...",
            clonedVoicesTitle: "Meine geklonten Stimmen",
            noClonedVoices: "Keine geklonten Stimmen",
            statusReady: "\u2705 Fertig",
            statusProcessing: "\u23F3 Wird verarbeitet",
            statusFailed: "\u274c Fehlgeschlagen",
            packagesTitle: "Audio Pakete",
            discountBadge: "Bis zu 30% Rabatt",
            buyPackageBtn: "Paket kaufen",
            libraryTitle: "Meine Audios",
            noAudio: "Kein Audio",
            createFirstAudio: "Erstellen Sie Ihr erstes Audio!",
            statusReady2: "Fertig",
            statusProcessing2: "In Bearbeitung",
            musicGenres: {
                electronic: "Elektronisch",
                rock: "Rock",
                jazz: "Jazz",
                classical: "Klassik",
                hiphop: "Hip-Hop",
                ambient: "Ambient"
            }
        }
    },
    es: {
        audioGen: {
            badge: "Estudio de Audio con IA",
            title: "Asistente ",
            titleHighlight: "de Audio",
            desc: "De texto a voz, música o clonación - crea audios profesionales",
            tabTTS: "Texto \u2192 Voz",
            tabMusic: "Crear Música",
            tabVoice: "Clonar Voz",
            tabPackages: "Paquetes",
            tabLibrary: "Mis Audios",
            ttsTitle: "Convertir Texto a Voz",
            ttsPlaceholder: "Escribe el texto aquí...",
            voiceCharacter: "Voz del Personaje",
            speed: "Velocidad",
            model: "Modelo",
            selectModel: "Modelo selecto",
            generateBtn: "Generar Audio",
            generating: "Generando...",
            popModelsTitle: "Modelos Populares",
            musicTitle: "Generador de Música IA",
            musicSelectGenre: "Elige el Género",
            musicMood: "Estado de ánimo",
            musicMoods: {
                happy: "Feliz",
                sad: "Triste",
                epic: "Épico",
                calm: "Tranquilo",
                energetic: "Energético",
                romantic: "Romántico"
            },
            musicPlaceholder: "Describe tu música...",
            musicGenerateBtn: "Generar Música",
            cloneTitle: "Clonación de Voz",
            cloneVoiceNameLabel: "Nombre de la Voz",
            cloneVoiceNamePlaceholder: "Ej: Mi Voz",
            cloneAudioFileLabel: "Archivo de Audio",
            cloneUploadClick: "Cargar muestra de voz",
            cloneUploadChange: "Clic para cambiar",
            cloneUploadReqs: "MP3, WAV \u2022 Min. 30 seg",
            cloneTipsTitle: "\ud83d\udca1 Consejos:",
            cloneTip1: "\u2022 Audio limpio y de calidad",
            cloneTip2: "\u2022 Evita ruido de fondo",
            cloneTip3: "\u2022 Min 30 seg, ideal 1-2 min",
            cloneBtn: "Clonar Voz",
            cloning: "Clonando...",
            clonedVoicesTitle: "Mis Voces Clonadas",
            noClonedVoices: "Aún no clonaste ninguna",
            statusReady: "\u2705 Listo",
            statusProcessing: "\u23F3 Procesando",
            statusFailed: "\u274c Fallido",
            packagesTitle: "Paquetes de Audio",
            discountBadge: "Hasta 30% desc",
            buyPackageBtn: "Comprar",
            libraryTitle: "Mis Audios",
            noAudio: "Sin audios",
            createFirstAudio: "¡Crea tu primer audio!",
            statusReady2: "Listo",
            statusProcessing2: "Procesando",
            musicGenres: {
                electronic: "Electrónica",
                rock: "Rock",
                jazz: "Jazz",
                classical: "Clásico",
                hiphop: "Hip-Hop",
                ambient: "Ambient"
            }
        }
    },
    zh: {
        audioGen: {
            badge: "人工智能音频工作室",
            title: "声音的 ",
            titleHighlight: "向导",
            desc: "从文本转语音、音乐生成到声音克隆——创造专业音频",
            tabTTS: "文字 \u2192 语音",
            tabMusic: "音乐产生",
            tabVoice: "语音克隆",
            tabPackages: "视听套餐",
            tabLibrary: "我的声音",
            ttsTitle: "将文本转换为语音",
            ttsPlaceholder: "写下您希望转换为语音的文本...",
            voiceCharacter: "声音角色",
            speed: "速度",
            model: "模型",
            selectModel: "选择型号",
            generateBtn: "生成音频",
            generating: "生成中...",
            popModelsTitle: "流行模型",
            musicTitle: "AI音乐创作",
            musicSelectGenre: "选择类型",
            musicMood: "心情",
            musicMoods: {
                happy: "快乐",
                sad: "忧伤",
                epic: "史诗",
                calm: "宁静",
                energetic: "充满活力",
                romantic: "浪漫"
            },
            musicPlaceholder: "分享您的音乐创意...",
            musicGenerateBtn: "生成音乐",
            cloneTitle: "语音克隆",
            cloneVoiceNameLabel: "配音名称",
            cloneVoiceNamePlaceholder: "例如：我的声音",
            cloneAudioFileLabel: "声音文件",
            cloneUploadClick: "点击上传语音样本",
            cloneUploadChange: "点击更改",
            cloneUploadReqs: "MP3, WAV \u2022 最短30秒",
            cloneTipsTitle: "\ud83d\udca1 提示：",
            cloneTip1: "\u2022 保持清晰",
            cloneTip2: "\u2022 避免背景噪音",
            cloneTip3: "\u2022 最短30秒，最理想是1-2分钟",
            cloneBtn: "克隆声音",
            cloning: "克隆中...",
            clonedVoicesTitle: "我克隆的声音",
            noClonedVoices: "您还没有克隆任何声音",
            statusReady: "\u2705 准备好",
            statusProcessing: "\u23F3 处理",
            statusFailed: "\u274c 失败",
            packagesTitle: "音频包",
            discountBadge: "最高九折起",
            buyPackageBtn: "获取包",
            libraryTitle: "我的配音",
            noAudio: "没有音频",
            createFirstAudio: "创建你的第一个配音！",
            statusReady2: "准备好",
            statusProcessing2: "进行",
            musicGenres: {
                electronic: "电子",
                rock: "摇滚",
                jazz: "爵士乐",
                classical: "古典的",
                hiphop: "嘻哈的",
                ambient: "环境音乐"
            }
        }
    },
    su: {
        audioGen: {
            badge: "An-na Gu-de Šà",
            title: "Gu ",
            titleHighlight: "En",
            desc: "Dub a gu-de, nar a gu-de - gu kal-ga",
            tabTTS: "Dub \u2192 Gu",
            tabMusic: "Nar Dù",
            tabVoice: "Gu Gibil",
            tabPackages: "Kaskal",
            tabLibrary: "Gu Mu",
            ttsTitle: "Dub a Gu Dù",
            ttsPlaceholder: "Sar dub gu-de...",
            voiceCharacter: "Gu Sag",
            speed: "Šid",
            model: "En",
            selectModel: "En pà",
            generateBtn: "Gu Dù",
            generating: "Dù-dù...",
            popModelsTitle: "En Gal",
            musicTitle: "An-na Nar Dù",
            musicSelectGenre: "Nar Pà",
            musicMood: "Zi",
            musicMoods: {
                happy: "Húl",
                sad: "Hul",
                epic: "Gal",
                calm: "Si-il",
                energetic: "Kal",
                romantic: "Ki-ág"
            },
            musicPlaceholder: "Sar nar zi...",
            musicGenerateBtn: "Nar Dù",
            cloneTitle: "Gu Gibil",
            cloneVoiceNameLabel: "Gu Mu",
            cloneVoiceNamePlaceholder: "Gu Mu Gibil",
            cloneAudioFileLabel: "Gu Dub",
            cloneUploadClick: "Gu ila",
            cloneUploadChange: "Gibil ila",
            cloneUploadReqs: "MP3, WAV",
            cloneTipsTitle: "\ud83d\udca1 Me:",
            cloneTip1: "\u2022 Gu dadag",
            cloneTip2: "\u2022 Nu gu-hul",
            cloneTip3: "\u2022 U4-gid",
            cloneBtn: "Gu Gibil Dù",
            cloning: "Dù-dù...",
            clonedVoicesTitle: "Mu Gu Gibil",
            noClonedVoices: "Nu gu gibil",
            statusReady: "\u2705 Šu-gar",
            statusProcessing: "\u23F3 Šid-da",
            statusFailed: "\u274c Hul",
            packagesTitle: "Kaskal",
            discountBadge: "Silim Gal",
            buyPackageBtn: "Sa10",
            libraryTitle: "Gu Mu",
            noAudio: "Nu gu",
            createFirstAudio: "Dù gu sag!",
            statusReady2: "Šu-gar",
            statusProcessing2: "Šid-da",
            musicGenres: {
                electronic: "Nim",
                rock: "Kala",
                jazz: "Zà",
                classical: "U4-ul",
                hiphop: "Ka",
                ambient: "A-ab"
            }
        }
    }
};

langs.forEach(lang => {
    const filePath = path.join(localesDir, `${lang}.json`);
    let data = {};
    if (fs.existsSync(filePath)) {
        try {
            data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        } catch (e) {
            console.error(`Error parsing ${filePath}`);
        }
    }
    data.audioGen = newKeys[lang].audioGen;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
