const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'frontend/src/i18n/locales');
const langs = ['en', 'tr', 'fr', 'de', 'es', 'zh', 'su'];

const newKeys = {
    en: {
        profile: {
            title: "Profile Settings",
            desc: "Manage your account information and security settings.",
            billingTitle: "Credits & Subscription",
            currentCredits: "Current Credits",
            mostPopular: "Most Popular",
            credits: "credits",
            discount: "Discount",
            processing: "Processing...",
            buy: "Buy",
            infoTitle: "Profile Information",
            fullName: "Full Name",
            email: "Email Address",
            role: "Role:",
            package: "Package:",
            save: "Save Changes",
            saving: "Saving...",
            changePassword: "Change Password",
            currentPassword: "Current Password",
            newPassword: "New Password",
            confirmPassword: "Confirm New Password",
            changing: "Changing..."
        },
        imageGen: {
            badge: "AI Image Generator",
            title: "Imagine, ",
            titleHighlight: "Create",
            desc: "Transform thoughts into stunning images in seconds",
            tabGenerate: "Generate",
            tabGallery: "Gallery",
            tabCompare: "Compare",
            modeText2Img: "Text \u2192 Image",
            modeImg2Img: "Image \u2192 Image",
            refImage: "Reference Image",
            uploadRef: "Upload reference image",
            dragDrop: "Drag & drop or click",
            strength: "Strength",
            lessChange: "Less change",
            moreChange: "More change",
            promptTitleT2I: "Write Prompt",
            promptTitleI2I: "Guidance Prompt",
            getInspiration: "Get Inspiration",
            clickToUse: "Click to use \u2192",
            promptPlaceholderT2I: "Describe the image of your dreams in detail...",
            promptPlaceholderI2I: "Describe how you want to transform the reference image...",
            modelTitle: "AI Model",
            selectModel: "Select model",
            credits: "credits",
            sizeTitle: "Size",
            generateBtnT2I: "Generate Image",
            generateBtnI2I: "Transform Image",
            generating: "Generating...",
            previewTitle: "Preview",
            previewGeneratingT2I: "Generating your image...",
            previewGeneratingI2I: "Transforming image...",
            waitSecs: "This may take a few seconds",
            download: "Download",
            fullscreen: "Fullscreen",
            emptyPreviewTitle: "You imagine, we create",
            emptyPreviewDesc: "Write a prompt on the left and watch AI magic",
            galleryTitle: "My Gallery",
            imagesCount: "images",
            refresh: "Refresh",
            loading: "Loading...",
            makeNft: "Make NFT",
            prevPage: "\u2190 Previous",
            page: "Page",
            nextPage: "Next \u2192",
            noImagesTitle: "No images yet",
            noImagesDesc: "Create your first image from the Generate tab",
            compareTitle: "Model Comparison",
            compareDesc: "Select multiple models with the same prompt and compare results side-by-side",
            selectModels: "Select Model (min 2, max 4)",
            comparePromptPlaceholder: "Describe the image you want to compare...",
            compareBtn: "Compare with Models",
            comparing: "Comparing...",
            model: "model"
        }
    },
    tr: {
        profile: {
            title: "Profil Ayarları",
            desc: "Hesap bilgilerinizi ve güvenlik ayarlarınızı yönetin.",
            billingTitle: "Kredi & Abonelik",
            currentCredits: "Mevcut Krediniz",
            mostPopular: "En Popüler",
            credits: "kredi",
            discount: "İndirim",
            processing: "İşleniyor...",
            buy: "Satın Al",
            infoTitle: "Profil Bilgileri",
            fullName: "Ad Soyad",
            email: "E-posta Adresi",
            role: "Rol:",
            package: "Paket:",
            save: "Değişiklikleri Kaydet",
            saving: "Kaydediliyor...",
            changePassword: "Şifre Değiştir",
            currentPassword: "Mevcut Şifre",
            newPassword: "Yeni Şifre",
            confirmPassword: "Yeni Şifre (Tekrar)",
            changing: "Değiştiriliyor..."
        },
        imageGen: {
            badge: "AI Görsel Üretici",
            title: "Hayal Et, ",
            titleHighlight: "Oluştur",
            desc: "Düşüncelerinizi saniyeler içinde etkileyici görsellere dönüştürün",
            tabGenerate: "Üret",
            tabGallery: "Galeri",
            tabCompare: "Karşılaştır",
            modeText2Img: "Metin \u2192 Görsel",
            modeImg2Img: "Görsel \u2192 Görsel",
            refImage: "Referans Görsel",
            uploadRef: "Referans görsel yükleyin",
            dragDrop: "Sürükle-bırak veya tıklayın",
            strength: "Dönüşüm Gücü",
            lessChange: "Az değişim",
            moreChange: "Çok değişim",
            promptTitleT2I: "Prompt Yaz",
            promptTitleI2I: "Yönlendirme Promptu",
            getInspiration: "İlham Al",
            clickToUse: "Kullanmak için tıkla \u2192",
            promptPlaceholderT2I: "Hayalinizdeki görseli detaylı bir şekilde tanımlayın...",
            promptPlaceholderI2I: "Referans görseli nasıl dönüştürmek istediğinizi yazın...",
            modelTitle: "AI Model",
            selectModel: "Model seçin",
            credits: "kredi",
            sizeTitle: "Boyut",
            generateBtnT2I: "Görsel Oluştur",
            generateBtnI2I: "Görseli Dönüştür",
            generating: "Oluşturuluyor...",
            previewTitle: "Önizleme",
            previewGeneratingT2I: "Görseliniz oluşturuluyor...",
            previewGeneratingI2I: "Görsel dönüştürülüyor...",
            waitSecs: "Bu birkaç saniye sürebilir",
            download: "İndir",
            fullscreen: "Tam Ekran",
            emptyPreviewTitle: "Hayal edin, biz oluşturalım",
            emptyPreviewDesc: "Sol taraftan bir prompt yazın ve AI'ın sihrini izleyin",
            galleryTitle: "Görsel Galerim",
            imagesCount: "görsel",
            refresh: "Yenile",
            loading: "Yükleniyor...",
            makeNft: "NFT Yap",
            prevPage: "\u2190 Önceki",
            page: "Sayfa",
            nextPage: "Sonraki \u2192",
            noImagesTitle: "Henüz görsel yok",
            noImagesDesc: "Üret sekmesinden ilk görselinizi oluşturun",
            compareTitle: "Model Karşılaştırma",
            compareDesc: "Aynı prompt ile birden fazla model seçip sonuçları yan yana karşılaştırın",
            selectModels: "Model Seçin (en az 2, en fazla 4)",
            comparePromptPlaceholder: "Karşılaştırmak istediğiniz görseli tanımlayın...",
            compareBtn: "Model ile Karşılaştır",
            comparing: "Karşılaştırılıyor...",
            model: "model"
        }
    },
    fr: {
        profile: {
            title: "Paramètres du profil",
            desc: "Gérez vos informations de compte et paramètres de sécurité.",
            billingTitle: "Crédits et abonnement",
            currentCredits: "Crédits actuels",
            mostPopular: "Le plus populaire",
            credits: "crédits",
            discount: "Réduction",
            processing: "Traitement...",
            buy: "Acheter",
            infoTitle: "Informations sur le profil",
            fullName: "Nom complet",
            email: "Adresse e-mail",
            role: "Rôle :",
            package: "Forfait :",
            save: "Enregistrer les modifications",
            saving: "Enregistrement...",
            changePassword: "Changer le mot de passe",
            currentPassword: "Mot de passe actuel",
            newPassword: "Nouveau mot de passe",
            confirmPassword: "Confirmer le nouveau mot de passe",
            changing: "Modification..."
        },
        imageGen: {
            badge: "Générateur d'images IA",
            title: "Imaginez, ",
            titleHighlight: "Créez",
            desc: "Transformez vos pensées en images époustouflantes en quelques secondes",
            tabGenerate: "Générer",
            tabGallery: "Galerie",
            tabCompare: "Comparer",
            modeText2Img: "Texte \u2192 Image",
            modeImg2Img: "Image \u2192 Image",
            refImage: "Image de référence",
            uploadRef: "Téléchargez l'image",
            dragDrop: "Glissez-déposez ou cliquez",
            strength: "Force",
            lessChange: "Moins",
            moreChange: "Plus",
            promptTitleT2I: "Écrire une invite",
            promptTitleI2I: "Invite de guidage",
            getInspiration: "Inspiration",
            clickToUse: "Cliquez pour utiliser \u2192",
            promptPlaceholderT2I: "Décrivez l'image de vos rêves...",
            promptPlaceholderI2I: "Décrivez comment transformer l'image...",
            modelTitle: "Modèle IA",
            selectModel: "Sélectionnez",
            credits: "crédits",
            sizeTitle: "Taille",
            generateBtnT2I: "Générer l'image",
            generateBtnI2I: "Transformer l'image",
            generating: "Génération...",
            previewTitle: "Aperçu",
            previewGeneratingT2I: "Génération en cours...",
            previewGeneratingI2I: "Transformation en cours...",
            waitSecs: "Cela peut prendre quelques secondes",
            download: "Télécharger",
            fullscreen: "Plein écran",
            emptyPreviewTitle: "Imaginez, nous créons",
            emptyPreviewDesc: "Écrivez une invite à gauche",
            galleryTitle: "Ma Galerie",
            imagesCount: "images",
            refresh: "Actualiser",
            loading: "Chargement...",
            makeNft: "Créer un NFT",
            prevPage: "\u2190 Précédent",
            page: "Page",
            nextPage: "Suivant \u2192",
            noImagesTitle: "Pas encore d'images",
            noImagesDesc: "Créez votre première image",
            compareTitle: "Comparaison",
            compareDesc: "Sélectionnez plusieurs modèles",
            selectModels: "Sélectionner un modèle",
            comparePromptPlaceholder: "Décrivez l'image...",
            compareBtn: "Comparer avec les modèles",
            comparing: "Comparaison en cours...",
            model: "modèle"
        }
    },
    de: {
        profile: {
            title: "Profileinstellungen",
            desc: "Verwalten Sie Ihre Kontoinformationen.",
            billingTitle: "Guthaben & Abonnement",
            currentCredits: "Aktuelles Guthaben",
            mostPopular: "Am beliebtesten",
            credits: "Credits",
            discount: "Rabatt",
            processing: "Verarbeitung...",
            buy: "Kaufen",
            infoTitle: "Profilinformationen",
            fullName: "Vollständiger Name",
            email: "E-Mail-Adresse",
            role: "Rolle:",
            package: "Paket:",
            save: "Änderungen speichern",
            saving: "Speichern...",
            changePassword: "Passwort ändern",
            currentPassword: "Aktuelles Passwort",
            newPassword: "Neues Passwort",
            confirmPassword: "Neues Passwort (bestätigen)",
            changing: "Ändern..."
        },
        imageGen: {
            badge: "KI-Bildgenerator",
            title: "Stell dir vor, ",
            titleHighlight: "Erstelle",
            desc: "Gedanken in atemberaubende Bilder verwandeln",
            tabGenerate: "Generieren",
            tabGallery: "Galerie",
            tabCompare: "Vergleichen",
            modeText2Img: "Text \u2192 Bild",
            modeImg2Img: "Bild \u2192 Bild",
            refImage: "Referenzbild",
            uploadRef: "Referenzbild hochladen",
            dragDrop: "Ziehen & Ablegen",
            strength: "Stärke",
            lessChange: "Weniger",
            moreChange: "Mehr",
            promptTitleT2I: "Prompt schreiben",
            promptTitleI2I: "Guidance Prompt",
            getInspiration: "Inspiration",
            clickToUse: "Hier klicken \u2192",
            promptPlaceholderT2I: "Beschreiben Sie das Bild...",
            promptPlaceholderI2I: "Beschreiben Sie die Transformation...",
            modelTitle: "KI-Modell",
            selectModel: "Modell auswählen",
            credits: "Credits",
            sizeTitle: "Größe",
            generateBtnT2I: "Bild generieren",
            generateBtnI2I: "Bild transformieren",
            generating: "Wird generiert...",
            previewTitle: "Vorschau",
            previewGeneratingT2I: "Bild wird erstellt...",
            previewGeneratingI2I: "Bild wird transformiert...",
            waitSecs: "Einen Moment...",
            download: "Herunterladen",
            fullscreen: "Vollbild",
            emptyPreviewTitle: "Du träumst, wir erschaffen",
            emptyPreviewDesc: "Schreibe einen Prompt",
            galleryTitle: "Meine Galerie",
            imagesCount: "Bilder",
            refresh: "Aktualisieren",
            loading: "Wird geladen...",
            makeNft: "NFT erstellen",
            prevPage: "\u2190 Zurück",
            page: "Seite",
            nextPage: "Weiter \u2192",
            noImagesTitle: "Noch keine Bilder",
            noImagesDesc: "Erstelle dein erstes Bild",
            compareTitle: "Vergleich",
            compareDesc: "Modelle vergleichen",
            selectModels: "Modell auswählen",
            comparePromptPlaceholder: "Bild beschreiben...",
            compareBtn: "Mit Modellen vergleichen",
            comparing: "Vergleichen...",
            model: "Modell"
        }
    },
    es: {
        profile: {
            title: "Ajustes de perfil",
            desc: "Administre la información de su cuenta y seguridad.",
            billingTitle: "Créditos y suscripción",
            currentCredits: "Créditos Actuales",
            mostPopular: "Más popular",
            credits: "créditos",
            discount: "Descuento",
            processing: "Procesando...",
            buy: "Comprar",
            infoTitle: "Información del perfil",
            fullName: "Nombre completo",
            email: "Correo electrónico",
            role: "Rol:",
            package: "Paquete:",
            save: "Guardar cambios",
            saving: "Guardando...",
            changePassword: "Cambiar la contraseña",
            currentPassword: "Contraseña actual",
            newPassword: "Nueva contraseña",
            confirmPassword: "Confirmar nueva contraseña",
            changing: "Cambiando..."
        },
        imageGen: {
            badge: "Generador de imágenes con IA",
            title: "Imagina, ",
            titleHighlight: "Crea",
            desc: "Transforma tus pensamientos en imágenes",
            tabGenerate: "Generar",
            tabGallery: "Galería",
            tabCompare: "Comparar",
            modeText2Img: "Texto \u2192 Imagen",
            modeImg2Img: "Imagen \u2192 Imagen",
            refImage: "Referencia",
            uploadRef: "Sube la imagen",
            dragDrop: "Arrastra y suelta",
            strength: "Fuerza",
            lessChange: "Menos",
            moreChange: "Más",
            promptTitleT2I: "Escribir Prompt",
            promptTitleI2I: "Escribir Guía",
            getInspiration: "Inspiración",
            clickToUse: "Haz clic \u2192",
            promptPlaceholderT2I: "Describe tu imagen...",
            promptPlaceholderI2I: "Describe la transformación...",
            modelTitle: "Modelo IA",
            selectModel: "Modelo",
            credits: "créditos",
            sizeTitle: "Tamaño",
            generateBtnT2I: "Generar",
            generateBtnI2I: "Transformar",
            generating: "Generando...",
            previewTitle: "Vista previa",
            previewGeneratingT2I: "Generando...",
            previewGeneratingI2I: "Transformando...",
            waitSecs: "Espera unos segundos",
            download: "Descargar",
            fullscreen: "Completa",
            emptyPreviewTitle: "Imagina y creamos",
            emptyPreviewDesc: "Escribe en el lado izquierdo",
            galleryTitle: "Mi Galería",
            imagesCount: "imágenes",
            refresh: "Recargar",
            loading: "Cargando...",
            makeNft: "Crear NFT",
            prevPage: "\u2190 Anterior",
            page: "Página",
            nextPage: "Siguiente \u2192",
            noImagesTitle: "Aún no hay imágenes",
            noImagesDesc: "Crea tu primera imagen",
            compareTitle: "Comparación",
            compareDesc: "Compara modelos",
            selectModels: "Modelos",
            comparePromptPlaceholder: "Describe...",
            compareBtn: "Comparar con Modelos",
            comparing: "Comparando...",
            model: "modelo"
        }
    },
    zh: {
        profile: {
            title: "配置文件设置",
            desc: "管理您的帐户信息和安全设置",
            billingTitle: "积分和订阅",
            currentCredits: "当前积分",
            mostPopular: "最受欢迎",
            credits: "积分",
            discount: "折扣",
            processing: "处理中...",
            buy: "购买",
            infoTitle: "资料信息",
            fullName: "全名",
            email: "电子邮件",
            role: "角色：",
            package: "包裹：",
            save: "保存更改",
            saving: "保存中...",
            changePassword: "更改密码",
            currentPassword: "当前密码",
            newPassword: "新密码",
            confirmPassword: "确认新密码",
            changing: "更改中..."
        },
        imageGen: {
            badge: "AI 图像生成器",
            title: "想象， ",
            titleHighlight: "创造",
            desc: "将想法变成令人惊叹的图像",
            tabGenerate: "生成",
            tabGallery: "图库",
            tabCompare: "比较",
            modeText2Img: "文本 \u2192 图像",
            modeImg2Img: "图像 \u2192 图像",
            refImage: "参考图像",
            uploadRef: "上传参考",
            dragDrop: "拖放或单击",
            strength: "强度",
            lessChange: "少",
            moreChange: "多",
            promptTitleT2I: "写提示",
            promptTitleI2I: "指导提示",
            getInspiration: "灵感",
            clickToUse: "点击使用 \u2192",
            promptPlaceholderT2I: "描述你梦想的图像...",
            promptPlaceholderI2I: "描述你想要如何转换图像...",
            modelTitle: "人工智能模型",
            selectModel: "选择模型",
            credits: "积分",
            sizeTitle: "大小",
            generateBtnT2I: "生成图像",
            generateBtnI2I: "转换图像",
            generating: "生成中...",
            previewTitle: "预览",
            previewGeneratingT2I: "正在生成...",
            previewGeneratingI2I: "转换中...",
            waitSecs: "等等...",
            download: "下载",
            fullscreen: "全屏",
            emptyPreviewTitle: "想象并创造",
            emptyPreviewDesc: "在左侧写提示",
            galleryTitle: "我的图库",
            imagesCount: "图片",
            refresh: "刷新",
            loading: "加载中...",
            makeNft: "创建 NFT",
            prevPage: "\u2190 上一页",
            page: "页",
            nextPage: "下一页 \u2192",
            noImagesTitle: "还没有图像",
            noImagesDesc: "创建您的第一张图像",
            compareTitle: "模型比较",
            compareDesc: "比较模型",
            selectModels: "选择模型 (2-4)",
            comparePromptPlaceholder: "描述你想比较的图像...",
            compareBtn: "与模型比较",
            comparing: "比较中...",
            model: "模型"
        }
    },
    su: {
        profile: {
            title: "Šà-bal-bal Ki",
            desc: "Mu-mu dub-sar",
            billingTitle: "Kug-sig Še",
            currentCredits: "Kug-sig Gal",
            mostPopular: "Dirig Zà-mí",
            credits: "Kug-sig",
            discount: "Silim",
            processing: "Šid...",
            buy: "Sa10",
            infoTitle: "Mu-mu Mu",
            fullName: "Mu Gal",
            email: "Kin-gi-a",
            role: "Me:",
            package: "Kaskal:",
            save: "Šid-Šid",
            saving: "Šid-da...",
            changePassword: "U-te Gibil",
            currentPassword: "U-te Gal",
            newPassword: "U-te Gibil",
            confirmPassword: "U-te Kišib",
            changing: "Šu-bal..."
        },
        imageGen: {
            badge: "An-na Alam Dù",
            title: "Šà-tuku, ",
            titleHighlight: "Dù",
            desc: "Šà na-ru-a alam gal-gal",
            tabGenerate: "Dù",
            tabGallery: "É-gal",
            tabCompare: "Ig-gi-in",
            modeText2Img: "Dub \u2192 Alam",
            modeImg2Img: "Alam \u2192 Alam",
            refImage: "Igi-kar Alam",
            uploadRef: "Ila Alam",
            dragDrop: "Kar-zi",
            strength: "Á",
            lessChange: "Tur",
            moreChange: "Gal",
            promptTitleT2I: "Sar Dub",
            promptTitleI2I: "Igi Dub",
            getInspiration: "Šu-gar",
            clickToUse: "Tag \u2192",
            promptPlaceholderT2I: "Alam me-a na-ru-a...",
            promptPlaceholderI2I: "Alam gibil me-a...",
            modelTitle: "An-na En",
            selectModel: "En Pà",
            credits: "kug",
            sizeTitle: "Gíd",
            generateBtnT2I: "Alam Dù",
            generateBtnI2I: "Alam Gibil",
            generating: "Dù-dù...",
            previewTitle: "Igi-kar",
            previewGeneratingT2I: "Alam dù-da...",
            previewGeneratingI2I: "Alam gibil-da...",
            waitSecs: "U-bi-a",
            download: "Šu-ti",
            fullscreen: "Gal Igi",
            emptyPreviewTitle: "An-na Šà",
            emptyPreviewDesc: "Šar dub, An-na dù",
            galleryTitle: "É-gal Mu",
            imagesCount: "alam",
            refresh: "Gibil",
            loading: "Šid...",
            makeNft: "NFT Dù",
            prevPage: "\u2190 U4",
            page: "Dub",
            nextPage: "U4 Gibil \u2192",
            noImagesTitle: "Nu Alam",
            noImagesDesc: "Dù alam",
            compareTitle: "Ig-gi-in En",
            compareDesc: "Ig-gi-in En-en",
            selectModels: "En Pà",
            comparePromptPlaceholder: "Dub Ig-gi-in...",
            compareBtn: "Ig-gi-in En",
            comparing: "Ig-gi-in-da...",
            model: "en"
        }
    }
};

langs.forEach(lang => {
    const filePath = path.join(localesDir, `${lang}.json`);
    let data = {};
    if (fs.existsSync(filePath)) {
        try {
            data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        } catch (e) {
            console.error(`Error parsing ${filePath}`);
        }
    }
    data.profile = newKeys[lang].profile;
    data.imageGen = newKeys[lang].imageGen;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
