const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'frontend/src/i18n/locales');
const langs = ['en', 'tr', 'fr', 'de', 'es', 'zh', 'su'];

const newKeys = {
    en: {
        videoGen: {
            badge: "AI Video Studio",
            title: "Video ",
            titleHighlight: "Wizard",
            desc: "Sora 2, Veo 3.1, Kling 2.6, Runway and more",
            tabT2V: "Text \u2192 Video",
            tabI2V: "Image \u2192 Video",
            tabV2V: "Video \u2192 Video",
            tabCompare: "Compare",
            tabEffects: "Effects",
            tabPackages: "Packages",
            tabGallery: "My Videos",
            t2vDesc: "Create video from text",
            i2vDesc: "Animate image",
            v2vDesc: "Transform video",
            compareDescModels: "Compare models",
            effectsDesc: "Video effects",
            packagesDesc: "Effect packages",
            galleryDesc: "My videos",
            modelsListT2V: "Text \u2192 Video Models",
            modelsListI2V: "Image \u2192 Video Models",
            modelsListV2V: "Video \u2192 Video Models",
            searchModel: "Search model...",
            modelCount: "models",
            noModelInCategory: "No models found in this category",
            startImage: "Start Image",
            uploadClickImage: "Click to upload image",
            uploadChangeImage: "Click to change",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "Source Video",
            uploadClickVideo: "Click to upload video",
            promptTitleT2V: "Video Scenario",
            promptTitleV2V: "Transformation Instruction",
            promptPlaceholderT2V: "Write a detailed description of your video...",
            promptPlaceholderV2V: "Write transformation instruction... (e.g., Change to anime style, make it nighttime)",
            styleTitle: "Style (Optional)",
            aspectRatio: "Aspect Ratio",
            generateBtnT2V: "Generate Video",
            generateBtnI2V: "Animate Image",
            generateBtnV2V: "Transform Video",
            generating: "Generating Video...",
            previewTitle: "Generated Video",
            previewGenerating: "Generating video...",
            previewWait: "Building video",
            statusCompleted: "\u2713 Ready",
            statusProcessing: "\u23F3 Processing",
            statusFailed: "\u2717 Error",
            statusPending: "\u23F3 Pending",
            download: "Download",
            close: "Close",
            compareTitle: "Compare Models",
            compareDesc: "Select 2-4 models and compare with the same prompt",
            comparePromptLabel: "Prompt (For all models)",
            comparePromptPlaceholder: "Enter description for the video you want to compare...",
            compareBtn: "Compare Models",
            compareResultsTitle: "Comparison Results",
            compareGenerating: "Initiating Comparison...",
            compareGenFailed: "Generation failed",
            effectsTitle: "Video Effects",
            effectsCount: "effects",
            effectsNoCat: "No effects in this category",
            applyEffect: "Apply Effect",
            applyingEffect: "Applying...",
            upload1stImage: "1st Image",
            upload2ndImage: "2nd Image",
            uploadImage: "Upload Image",
            selectEffectHelp: "Select an effect from the left to start",
            selectEffectTitle: "Select Effect",
            packagesTitle: "Effect Packages",
            packagesNoCat: "No packages yet",
            packageIncludedEffects: "Included Effects",
            packageTotalSavings: "Total Savings",
            packageYouSave: "You save",
            buyPackage: "Buy Package",
            selectPackageHelp: "Select a package from the left to view details",
            selectPackageTitle: "Select Package",
            galleryTitle: "My Videos",
            galleryNoVideos: "No videos yet",
            galleryCreateFirst: "Create your first video!",
            videoError: "Video Failed",
            share: "Share",
            copyLink: "Copy Link",
            linkCopied: "Link copied!"
        }
    },
    tr: {
        videoGen: {
            badge: "AI Video Stüdyosu",
            title: "Video ",
            titleHighlight: "Sihirbazı",
            desc: "Sora 2, Veo 3.1, Kling 2.6, Runway ve daha fazlası",
            tabT2V: "Metin \u2192 Video",
            tabI2V: "Görsel \u2192 Video",
            tabV2V: "Video \u2192 Video",
            tabCompare: "Karşılaştır",
            tabEffects: "Efektler",
            tabPackages: "Paketler",
            tabGallery: "Videolarım",
            t2vDesc: "Metinden video oluştur",
            i2vDesc: "Görseli hareketlendir",
            v2vDesc: "Videoyu dönüştür",
            compareDescModels: "Modelleri karşılaştır",
            effectsDesc: "Video efektleri",
            packagesDesc: "Efekt paketleri",
            galleryDesc: "Videolarım",
            modelsListT2V: "Text \u2192 Video Modeller",
            modelsListI2V: "Image \u2192 Video Modeller",
            modelsListV2V: "Video \u2192 Video Modeller",
            searchModel: "Model ara...",
            modelCount: "model",
            noModelInCategory: "Bu kategoride model bulunamadı",
            startImage: "Başlangıç Görseli",
            uploadClickImage: "Görsel yüklemek için tıklayın",
            uploadChangeImage: "Değiştirmek için tıklayın",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "Kaynak Video",
            uploadClickVideo: "Video yüklemek için tıklayın",
            promptTitleT2V: "Video Senaryosu",
            promptTitleV2V: "Dönüşüm Talimatı",
            promptPlaceholderT2V: "Videonuzun detaylı bir tanımını yazın...",
            promptPlaceholderV2V: "Dönüşüm talimatı yazın... (Örn: Anime stiline çevir, gece vakti yap)",
            styleTitle: "Stil (Opsiyonel)",
            aspectRatio: "En-Boy Oranı",
            generateBtnT2V: "Video Oluştur",
            generateBtnI2V: "Görseli Hareketlendir",
            generateBtnV2V: "Videoyu Dönüştür",
            generating: "Video Oluşturuluyor...",
            previewTitle: "Üretilen Video",
            previewGenerating: "Video üretiliyor...",
            previewWait: "Oluşturuluyor...",
            statusCompleted: "\u2713 Hazır",
            statusProcessing: "\u23F3 İşleniyor",
            statusFailed: "\u2717 Hata",
            statusPending: "\u23F3 Bekliyor",
            download: "İndir",
            close: "Kapat",
            compareTitle: "Modelleri Karşılaştır",
            compareDesc: "2-4 model seçin ve aynı prompt ile karşılaştırın",
            comparePromptLabel: "Prompt (Tüm modeller için)",
            comparePromptPlaceholder: "Karşılaştırmak istediğiniz video için açıklama girin...",
            compareBtn: "Karşılaştır",
            compareResultsTitle: "Karşılaştırma Sonuçları",
            compareGenerating: "Karşılaştırma Başlatılıyor...",
            compareGenFailed: "Üretim başarısız",
            effectsTitle: "Video Efektleri",
            effectsCount: "efekt",
            effectsNoCat: "Bu kategoride efekt yok",
            applyEffect: "Efekt Uygula",
            applyingEffect: "İşleniyor...",
            upload1stImage: "1. Görsel",
            upload2ndImage: "2. Görsel",
            uploadImage: "Görsel Yükle",
            selectEffectHelp: "Sol taraftan bir efekt seçerek başlayın",
            selectEffectTitle: "Efekt Seçin",
            packagesTitle: "Efekt Paketleri",
            packagesNoCat: "Henüz paket yok",
            packageIncludedEffects: "Pakete Dahil Efektler",
            packageTotalSavings: "Toplam Tasarruf",
            packageYouSave: "kazanıyorsunuz!",
            buyPackage: "Paketi Satın Al",
            selectPackageHelp: "Sol taraftan bir paket seçerek detayları görüntüleyin",
            selectPackageTitle: "Paket Seçin",
            galleryTitle: "Videolarım",
            galleryNoVideos: "Henüz video yok",
            galleryCreateFirst: "İlk videonuzu oluşturun!",
            videoError: "Video Başarısız",
            share: "Paylaş",
            copyLink: "Linki Kopyala",
            linkCopied: "Link kopyalandı!"
        }
    },
    fr: {
        videoGen: {
            badge: "Studio Vidéo IA",
            title: "Assistant ",
            titleHighlight: "Vidéo",
            desc: "Sora 2, Veo 3.1, Kling 2.6, Runway et plus",
            tabT2V: "Texte \u2192 Vidéo",
            tabI2V: "Image \u2192 Vidéo",
            tabV2V: "Vidéo \u2192 Vidéo",
            tabCompare: "Comparer",
            tabEffects: "Effets",
            tabPackages: "Forfaits",
            tabGallery: "Mes vidéos",
            t2vDesc: "Créer une vidéo à partir d'un texte",
            i2vDesc: "Animer une image",
            v2vDesc: "Transformer la vidéo",
            compareDescModels: "Comparer les modèles",
            effectsDesc: "Effets vidéo",
            packagesDesc: "Forfaits d'effets",
            galleryDesc: "Mes vidéos",
            modelsListT2V: "Texte \u2192 Modèles Vidéo",
            modelsListI2V: "Image \u2192 Modèles Vidéo",
            modelsListV2V: "Vidéo \u2192 Modèles Vidéo",
            searchModel: "Rechercher un modèle...",
            modelCount: "modèles",
            noModelInCategory: "Aucun modèle trouvé dans cette catégorie",
            startImage: "Image de départ",
            uploadClickImage: "Cliquez pour télécharger l'image",
            uploadChangeImage: "Cliquer pour changer",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "Vidéo source",
            uploadClickVideo: "Cliquez pour télécharger la vidéo",
            promptTitleT2V: "Scénario Vidéo",
            promptTitleV2V: "Instructions de Transformation",
            promptPlaceholderT2V: "Écrivez une description détaillée de votre vidéo...",
            promptPlaceholderV2V: "Écrivez les instructions... (ex: Style animé, mode nuit)",
            styleTitle: "Style (Optionnel)",
            aspectRatio: "Ratio d'aspect",
            generateBtnT2V: "Générer la vidéo",
            generateBtnI2V: "Animer l'image",
            generateBtnV2V: "Transformer la vidéo",
            generating: "Génération en cours...",
            previewTitle: "Vidéo générée",
            previewGenerating: "Génération de la vidéo en cours...",
            previewWait: "Création de la vidéo",
            statusCompleted: "\u2713 Prêt",
            statusProcessing: "\u23F3 En cours",
            statusFailed: "\u2717 Erreur",
            statusPending: "\u23F3 En attente",
            download: "Télécharger",
            close: "Fermer",
            compareTitle: "Comparer les modèles",
            compareDesc: "Sélectionnez 2-4 modèles et comparez avec la même invite",
            comparePromptLabel: "Invite (Pour tous les modèles)",
            comparePromptPlaceholder: "Entrez la description de la vidéo à comparer...",
            compareBtn: "Comparer",
            compareResultsTitle: "Résultats",
            compareGenerating: "Initialisation...",
            compareGenFailed: "Génération échouée",
            effectsTitle: "Effets vidéo",
            effectsCount: "effets",
            effectsNoCat: "Aucun effet ici",
            applyEffect: "Appliquer l'effet",
            applyingEffect: "Application...",
            upload1stImage: "1ère image",
            upload2ndImage: "2ème image",
            uploadImage: "Télécharger",
            selectEffectHelp: "Sélectionnez un effet à gauche",
            selectEffectTitle: "Sélectionner un effet",
            packagesTitle: "Forfaits",
            packagesNoCat: "Aucun forfait",
            packageIncludedEffects: "Effets inclus",
            packageTotalSavings: "Économies",
            packageYouSave: "sauvé!",
            buyPackage: "Acheter le forfait",
            selectPackageHelp: "Sélectionnez un forfait à gauche",
            selectPackageTitle: "Sélectionner le forfait",
            galleryTitle: "Mes vidéos",
            galleryNoVideos: "Aucune vidéo",
            galleryCreateFirst: "Créez votre première vidéo!",
            videoError: "Erreur vidéo",
            share: "Partager",
            copyLink: "Copier le lien",
            linkCopied: "Lien copié!"
        }
    },
    de: {
        videoGen: {
            badge: "KI Video Studio",
            title: "Video ",
            titleHighlight: "Assistent",
            desc: "Sora 2, Veo 3.1, Kling 2.6, Runway und mehr",
            tabT2V: "Text \u2192 Video",
            tabI2V: "Bild \u2192 Video",
            tabV2V: "Video \u2192 Video",
            tabCompare: "Vergleichen",
            tabEffects: "Effekte",
            tabPackages: "Pakete",
            tabGallery: "Meine Videos",
            t2vDesc: "Video aus Text",
            i2vDesc: "Bild animieren",
            v2vDesc: "Video transformieren",
            compareDescModels: "Modelle vergleichen",
            effectsDesc: "Videoeffekte",
            packagesDesc: "Effektpakete",
            galleryDesc: "Meine Videos",
            modelsListT2V: "Text \u2192 Video Modelle",
            modelsListI2V: "Bild \u2192 Video Modelle",
            modelsListV2V: "Video \u2192 Video Modelle",
            searchModel: "Modell suchen...",
            modelCount: "Modelle",
            noModelInCategory: "Keine Modelle gefunden",
            startImage: "Startbild",
            uploadClickImage: "Klicken zum Hochladen",
            uploadChangeImage: "Klicken zum Ändern",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "Quellvideo",
            uploadClickVideo: "Klicken zum Hochladen",
            promptTitleT2V: "Videoszenario",
            promptTitleV2V: "Transformationsanweisung",
            promptPlaceholderT2V: "Schreiben Sie eine detaillierte Beschreibung...",
            promptPlaceholderV2V: "Anweisungen schreiben...",
            styleTitle: "Stil (Optional)",
            aspectRatio: "Seitenverhältnis",
            generateBtnT2V: "Video generieren",
            generateBtnI2V: "Bild animieren",
            generateBtnV2V: "Video transformieren",
            generating: "Wird generiert...",
            previewTitle: "Generiertes Video",
            previewGenerating: "Video wird erstellt...",
            previewWait: "Bitte warten...",
            statusCompleted: "\u2713 Fertig",
            statusProcessing: "\u23F3 In Bearbeitung",
            statusFailed: "\u2717 Fehler",
            statusPending: "\u23F3 Ausstehend",
            download: "Herunterladen",
            close: "Schließen",
            compareTitle: "Vergleichen",
            compareDesc: "Wählen Sie Modelle",
            comparePromptLabel: "Prompt",
            comparePromptPlaceholder: "Beschreibung eingeben...",
            compareBtn: "Vergleichen",
            compareResultsTitle: "Ergebnisse",
            compareGenerating: "Vergleich startet...",
            compareGenFailed: "Fehlgeschlagen",
            effectsTitle: "Videoeffekte",
            effectsCount: "Effekte",
            effectsNoCat: "Keine Effekte hier",
            applyEffect: "Effekt anwenden",
            applyingEffect: "Wird angewendet...",
            upload1stImage: "1. Bild",
            upload2ndImage: "2. Bild",
            uploadImage: "Bild hochladen",
            selectEffectHelp: "Wählen Sie einen Effekt",
            selectEffectTitle: "Effekt wählen",
            packagesTitle: "Pakete",
            packagesNoCat: "Keine Pakete",
            packageIncludedEffects: "Enthaltene Effekte",
            packageTotalSavings: "Ersparnis",
            packageYouSave: "gespart!",
            buyPackage: "Paket kaufen",
            selectPackageHelp: "Wählen Sie ein Paket",
            selectPackageTitle: "Paket wählen",
            galleryTitle: "Meine Videos",
            galleryNoVideos: "Noch keine Videos",
            galleryCreateFirst: "Erstellen Sie Ihr erstes Video!",
            videoError: "Video Fehler",
            share: "Teilen",
            copyLink: "Link kopieren",
            linkCopied: "Link kopiert!"
        }
    },
    es: {
        videoGen: {
            badge: "Estudio de Video con IA",
            title: "Asistente ",
            titleHighlight: "de Video",
            desc: "Sora 2, Veo 3.1, Kling 2.6, Runway y más",
            tabT2V: "Texto \u2192 VIdeo",
            tabI2V: "Imagen \u2192 Video",
            tabV2V: "Video \u2192 Video",
            tabCompare: "Comparar",
            tabEffects: "Efectos",
            tabPackages: "Paquetes",
            tabGallery: "Mis videos",
            t2vDesc: "Crear video",
            i2vDesc: "Animar",
            v2vDesc: "Transformar",
            compareDescModels: "Comparar modelos",
            effectsDesc: "Efectos",
            packagesDesc: "Paquetes",
            galleryDesc: "Mis videos",
            modelsListT2V: "Texto \u2192 Modelos",
            modelsListI2V: "Imagen \u2192 Modelos",
            modelsListV2V: "Video \u2192 Modelos",
            searchModel: "Buscar modelo...",
            modelCount: "modelos",
            noModelInCategory: "No se encontraron modelos",
            startImage: "Imagen inicial",
            uploadClickImage: "Clic para subir",
            uploadChangeImage: "Clic para cambiar",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "Video fuente",
            uploadClickVideo: "Clic para subir",
            promptTitleT2V: "Guion del video",
            promptTitleV2V: "Instrucción de conversión",
            promptPlaceholderT2V: "Escribe una descripción...",
            promptPlaceholderV2V: "Escribe instrucciones...",
            styleTitle: "Estilo (Opcional)",
            aspectRatio: "Relación de aspecto",
            generateBtnT2V: "Generar Video",
            generateBtnI2V: "Animar Imagen",
            generateBtnV2V: "Transformar Video",
            generating: "Generando...",
            previewTitle: "Video generado",
            previewGenerating: "Generando...",
            previewWait: "Espera...",
            statusCompleted: "\u2713 Listo",
            statusProcessing: "\u23F3 Procesando",
            statusFailed: "\u2717 Error",
            statusPending: "\u23F3 Pendiente",
            download: "Descargar",
            close: "Cerrar",
            compareTitle: "Comparar Modelos",
            compareDesc: "Selecciona modelos",
            comparePromptLabel: "Prompt",
            comparePromptPlaceholder: "Ingresar descripción...",
            compareBtn: "Comparar",
            compareResultsTitle: "Resultados",
            compareGenerating: "Iniciando...",
            compareGenFailed: "Fallido",
            effectsTitle: "Efectos",
            effectsCount: "efectos",
            effectsNoCat: "Sin efectos",
            applyEffect: "Aplicar efecto",
            applyingEffect: "Aplicando...",
            upload1stImage: "1ra Imagen",
            upload2ndImage: "2da Imagen",
            uploadImage: "Subir Imagen",
            selectEffectHelp: "Selecciona un efecto",
            selectEffectTitle: "Seleccionar Efecto",
            packagesTitle: "Paquetes",
            packagesNoCat: "Sin paquetes",
            packageIncludedEffects: "Efectos",
            packageTotalSavings: "Ahorro",
            packageYouSave: "¡ahorras!",
            buyPackage: "Comprar",
            selectPackageHelp: "Selecciona un paquete",
            selectPackageTitle: "Seleccionar Paquete",
            galleryTitle: "Mis Videos",
            galleryNoVideos: "Sin videos",
            galleryCreateFirst: "¡Crea tu primer video!",
            videoError: "Error de Video",
            share: "Compartir",
            copyLink: "Copiar enlace",
            linkCopied: "¡Enlace copiado!"
        }
    },
    zh: {
        videoGen: {
            badge: "人工智能视频工作室",
            title: "视频 ",
            titleHighlight: "向导",
            desc: "Sora 2、Veo 3.1、Kling 2.6、Runway 等",
            tabT2V: "文字 \u2192 视频",
            tabI2V: "图像 \u2192 视频",
            tabV2V: "视频 \u2192 视频",
            tabCompare: "比较",
            tabEffects: "效果",
            tabPackages: "套餐",
            tabGallery: "我的视频",
            t2vDesc: "视频创建",
            i2vDesc: "动画",
            v2vDesc: "转型",
            compareDescModels: "比较模型",
            effectsDesc: "影片特效",
            packagesDesc: "效果包",
            galleryDesc: "我的视频",
            modelsListT2V: "文本\u2192视频模型",
            modelsListI2V: "图像\u2192视频模型",
            modelsListV2V: "视频\u2192视频模型",
            searchModel: "搜索模型...",
            modelCount: "模型",
            noModelInCategory: "没找到",
            startImage: "起始图像",
            uploadClickImage: "点击上传图片",
            uploadChangeImage: "点击改变",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "来源视频",
            uploadClickVideo: "点击上传",
            promptTitleT2V: "视频场景",
            promptTitleV2V: "转换说明",
            promptPlaceholderT2V: "写下您视频的详细...",
            promptPlaceholderV2V: "写说明...",
            styleTitle: "风格",
            aspectRatio: "纵横比",
            generateBtnT2V: "生成视频",
            generateBtnI2V: "设置图像动画",
            generateBtnV2V: "变换视频",
            generating: "生成中...",
            previewTitle: "视频已生成",
            previewGenerating: "正在生成...",
            previewWait: "等...",
            statusCompleted: "\u2713 准备好",
            statusProcessing: "\u23F3 处理",
            statusFailed: "\u2717 错误",
            statusPending: "\u23F3 待办",
            download: "下载",
            close: "关闭",
            compareTitle: "比较模型",
            compareDesc: "选择型号",
            comparePromptLabel: "提示",
            comparePromptPlaceholder: "输入说明...",
            compareBtn: "比较",
            compareResultsTitle: "结果",
            compareGenerating: "启动...",
            compareGenFailed: "失败",
            effectsTitle: "效果",
            effectsCount: "效果",
            effectsNoCat: "无效果",
            applyEffect: "应用",
            applyingEffect: "应用中...",
            upload1stImage: "第一张图片",
            upload2ndImage: "第二张图片",
            uploadImage: "上传",
            selectEffectHelp: "选择一种效果",
            selectEffectTitle: "选择效果",
            packagesTitle: "套餐",
            packagesNoCat: "无包裹",
            packageIncludedEffects: "包含的影响",
            packageTotalSavings: "节省",
            packageYouSave: "保！",
            buyPackage: "购买包裹",
            selectPackageHelp: "选择包裹",
            selectPackageTitle: "套餐",
            galleryTitle: "我的影片",
            galleryNoVideos: "没有影片",
            galleryCreateFirst: "打造你的第一个影片！",
            videoError: "影片错误",
            share: "分享",
            copyLink: "复制",
            linkCopied: "复制链接！"
        }
    },
    su: {
        videoGen: {
            badge: "An-na Igi-gál Šà",
            title: "Igi ",
            titleHighlight: "En",
            desc: "Sora 2, Veo 3.1, Kling 2.6, Runway",
            tabT2V: "Dub \u2192 Igi",
            tabI2V: "Alam \u2192 Igi",
            tabV2V: "Igi \u2192 Igi",
            tabCompare: "Ig-gi-in",
            tabEffects: "Me",
            tabPackages: "Kaskal",
            tabGallery: "Igi Mu",
            t2vDesc: "Dub dù igi",
            i2vDesc: "Alam dù",
            v2vDesc: "Igi gibil",
            compareDescModels: "Ig-gi-in en",
            effectsDesc: "Igi me",
            packagesDesc: "Kaskal me",
            galleryDesc: "Igi mu",
            modelsListT2V: "Dub \u2192 Igi En",
            modelsListI2V: "Alam \u2192 Igi En",
            modelsListV2V: "Igi \u2192 Igi En",
            searchModel: "En kin...",
            modelCount: "en",
            noModelInCategory: "Nu en",
            startImage: "Alam Sag",
            uploadClickImage: "Alam ila",
            uploadChangeImage: "Gibil ila",
            formatsImage: "PNG, JPG, WebP",
            formatsVideo: "MP4, MOV, WebM",
            sourceVideo: "Igi Sag",
            uploadClickVideo: "Igi ila",
            promptTitleT2V: "Igi Dub",
            promptTitleV2V: "Gibil Dub",
            promptPlaceholderT2V: "Sar dub igi...",
            promptPlaceholderV2V: "Sar dub gibil...",
            styleTitle: "Zà (Nu-al)",
            aspectRatio: "Šid",
            generateBtnT2V: "Igi Dù",
            generateBtnI2V: "Alam Dù",
            generateBtnV2V: "Igi Gibil",
            generating: "Dù-dù...",
            previewTitle: "Igi Dù",
            previewGenerating: "Igi dù-da...",
            previewWait: "U4-da...",
            statusCompleted: "\u2713 Šu-gar",
            statusProcessing: "\u23F3 Šid-da",
            statusFailed: "\u2717 Hul",
            statusPending: "\u23F3 U4",
            download: "Šu-ti",
            close: "Tab",
            compareTitle: "Ig-gi-in En",
            compareDesc: "Ig-gi-in en-en",
            comparePromptLabel: "Dub",
            comparePromptPlaceholder: "Sar ig-gi-in...",
            compareBtn: "Ig-gi-in",
            compareResultsTitle: "Ig-gi-in Gal",
            compareGenerating: "Ig-gi-in-da...",
            compareGenFailed: "Nu dù",
            effectsTitle: "Me",
            effectsCount: "me",
            effectsNoCat: "Nu me",
            applyEffect: "Me Gar",
            applyingEffect: "Gar-da...",
            upload1stImage: "1 Alam",
            upload2ndImage: "2 Alam",
            uploadImage: "Alam Ila",
            selectEffectHelp: "Me pà",
            selectEffectTitle: "Me Pà",
            packagesTitle: "Kaskal",
            packagesNoCat: "Nu kaskal",
            packageIncludedEffects: "Kaskal Me",
            packageTotalSavings: "Silim Gal",
            packageYouSave: "silim!",
            buyPackage: "Sa10 Kaskal",
            selectPackageHelp: "Kaskal pà",
            selectPackageTitle: "Kaskal",
            galleryTitle: "Igi Mu",
            galleryNoVideos: "Nu igi",
            galleryCreateFirst: "Dù igi sag!",
            videoError: "Igi Hul",
            share: "Šil",
            copyLink: "Šu-ti Kad",
            linkCopied: "Kad šu-ti!"
        }
    }
};

langs.forEach(lang => {
    const filePath = path.join(localesDir, `${lang}.json`);
    let data = {};
    if (fs.existsSync(filePath)) {
        try {
            data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        } catch (e) {
            console.error(`Error parsing ${filePath}`);
        }
    }
    data.videoGen = newKeys[lang].videoGen;
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
});
